name: Build and Release EXE

on:
  push:
    tags:
      - 'v*' # Τρέχει μόνο όταν κάνεις push ένα tag που ξεκινάει με v (π.χ. v1.0)

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write # Απαραίτητο για να μπορεί το Action να δημιουργήσει το Release

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cryptography pyautogui pyinstaller

    - name: Build Manager EXE
      run: |
        pyinstaller --onefile --noconsole --add-data "manager.ico;." --icon="manager.ico" manager.py

    - name: Build Launcher EXE
      run: |
        pyinstaller --onefile --noconsole --add-data "launcher.ico;." --icon="launcher.ico" launcher.py

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/manager.exe
          dist/lancher.exe
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
